name: hma-dynamicvit
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::pytorch-cuda=11.7
  - defaults::mkl=2024.0
  - numpy<2
  - pillow
  - pyyaml
  - pip:
      - timm==0.3.2
      - tensorboardX
      - six
      - fvcore
