name: hma-hat
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - pytorch::pytorch-cuda=11.7
  - "defaults::mkl<2024.1"
  - gcc_linux-64
  - gxx_linux-64
  - ninja
  - numpy<2
  - pillow
  - pyyaml
  - pip:
      - opencv-python
      - scipy
      - cython
