name: hma-mambavision
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - cuda-nvcc=12.4
  - cuda-cudart-dev=12.4
  - gcc_linux-64=13
  - gxx_linux-64=13
  - ninja
  - packaging
  - numpy
  - pillow
  - pyyaml
  - pip:
      - timm==1.0.15
      - transformers==4.50.0
      - huggingface-hub
      - einops
